//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectMaps.Pages
{
    using WatiN.Core;

    public abstract class ApplicationMailingAddressUpdateControls : BasePageControls
    {
        [FindBy(Id = "ctl00_Main_ddlCorrespondenceMedium")]
        protected SelectList ddlCorrespondenceMedium { get; set; }

        [FindBy(Id = "ctl00_Main_ddlCorrespondenceMailAddress")]
        protected SelectList ddlCorrespondenceMailAddress { get; set; }

        [FindBy(Id = "ctl00_Main_ddlMailingAddress")]
        protected SelectList ddlMailingAddress { get; set; }

        [FindBy(Id = "ctl00_Main_ddlCorrespondenceLanguage")]
        protected SelectList ddlCorrespondenceLanguage { get; set; }

        [FindBy(Id = "ctl00_Main_chkOnlineStatement")]
        protected CheckBox chkOnlineStatement { get; set; }

        [FindBy(Id = "ctl00_Main_ddlOnlineStatementFormat")]
        protected SelectList ddlOnlineStatementFormat { get; set; }

        [FindBy(Id = "ctl00_Main_CancelButton")]
        protected Button btnCancel { get; set; }

        [FindBy(Id = "ctl00_Main_SubmitButton")]
        protected Button btnSubmit { get; set; }
    }
}