using Machine.Specifications;

namespace WorkflowMaps.Credit.Specs.Activities.Move_from_Origination.OnStart
{
    [Subject("Activity => Move_from_Origination => OnStart")] // AutoGenerated
    internal class when_move_from_origination : WorkflowSpecCredit
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Move_from_Origination(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}