//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("ProcessBankLiveReplies.Reply", Namespace="", IsNullable=false)]
public partial class ProcessBankLiveRepliesReply {
    
    private ProcessBankLiveRepliesReplyServiceHeader serviceHeaderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Service.Header")]
    public ProcessBankLiveRepliesReplyServiceHeader ServiceHeader {
        get {
            return this.serviceHeaderField;
        }
        set {
            this.serviceHeaderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProcessBankLiveRepliesReplyServiceHeader {
    
    private System.DateTime replyDateTimeField;
    
    private string serviceResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reply.DateTime")]
    public System.DateTime ReplyDateTime {
        get {
            return this.replyDateTimeField;
        }
        set {
            this.replyDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Service.Result", DataType="nonNegativeInteger")]
    public string ServiceResult {
        get {
            return this.serviceResultField;
        }
        set {
            this.serviceResultField = value;
        }
    }
}
