//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.190
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Web.Views.Common {
    
    
    /// <summary>
    /// ValuationLightstoneView class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class ValuationLightstoneView {
        
        /// <summary>
        /// Tabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabContainer Tabs;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel Panel1;
        
        /// <summary>
        /// pnlInspectionContactDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlInspectionContactDetails;
        
        /// <summary>
        /// _lblReferenceNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblReferenceNumber;
        
        /// <summary>
        /// lblReferenceNumberValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblReferenceNumberValue;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel Label2;
        
        /// <summary>
        /// lblERFSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblERFSize;
        
        /// <summary>
        /// _lblAutomatedValueDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblAutomatedValueDate;
        
        /// <summary>
        /// lblAutomatedValueDateValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblAutomatedValueDateValue;
        
        /// <summary>
        /// lblLastSaleDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblLastSaleDate;
        
        /// <summary>
        /// lblLastSaleDateValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblLastSaleDateValue;
        
        /// <summary>
        /// _lblEstimatedMarketValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblEstimatedMarketValue;
        
        /// <summary>
        /// lblEstimatedMarketValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblEstimatedMarketValue;
        
        /// <summary>
        /// _lblLastSalePrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblLastSalePrice;
        
        /// <summary>
        /// lblLastSalePriceValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblLastSalePriceValue;
        
        /// <summary>
        /// _lblConfidenceScore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblConfidenceScore;
        
        /// <summary>
        /// lblConfidenceScoreValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblConfidenceScoreValue;
        
        /// <summary>
        /// _lblAreaQualityGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblAreaQualityGrade;
        
        /// <summary>
        /// lblAreaQualityGradeValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblAreaQualityGradeValue;
        
        /// <summary>
        /// _lblExpectedHighValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblExpectedHighValue;
        
        /// <summary>
        /// lblExpectedHighValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblExpectedHighValue;
        
        /// <summary>
        /// lblAreaExposure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblAreaExposure;
        
        /// <summary>
        /// lblAreaExposureValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblAreaExposureValue;
        
        /// <summary>
        /// _lblExpectedLowValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblExpectedLowValue;
        
        /// <summary>
        /// lblExpectedLowValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblExpectedLowValue;
        
        /// <summary>
        /// _lblAutomatedValuationDecision control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel _lblAutomatedValuationDecision;
        
        /// <summary>
        /// lblAutomatedValuationDecisionValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel lblAutomatedValuationDecisionValue;
        
        /// <summary>
        /// pnlOwners control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlOwners;
        
        /// <summary>
        /// grdOwners control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLGridView grdOwners;
        
        /// <summary>
        /// Panel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel Panel3;
        
        /// <summary>
        /// grdComparativeSales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLGridView grdComparativeSales;
        
        /// <summary>
        /// Panel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel Panel2;
        
        /// <summary>
        /// pnlMaps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlMaps;
        
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLLabel Label1;
        
        /// <summary>
        /// ddlMapProvider control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlMapProvider;
        
        /// <summary>
        /// Panel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel4;
        
        /// <summary>
        /// MapLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal MapLiteral;
        
        /// <summary>
        /// btnBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SAHL.Common.Web.UI.Controls.SAHLButton btnBack;
    }
}
