using Machine.Specifications;
using SAHL.WorkflowMaps.LifeClaims.Specs;

namespace WorkflowMaps.DisabilityClaim.Specs.Activities.EXT_Claim_Settled.OnComplete
{
    [Subject("Activity => EXT_Claim_Settled => OnComplete")] // AutoGenerated
    internal class when_ext_claim_settled : WorkflowSpecDisabilityClaim
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
			string message = string.Empty;
            result = workflow.OnCompleteActivity_EXT_Claim_Settled(instanceData, workflowData, paramsData, messages, ref message);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}