using Machine.Specifications;

namespace WorkflowMaps.Life.Specs.Activities.Accept_Exclusions.OnStart
{
    [Subject("Activity => Accept_Exclusions => OnStart")] // AutoGenerated
    internal class when_accept_exclusions : WorkflowSpecLife
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Accept_Exclusions(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}