using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Capture_Recoveries_Proposal.OnComplete
{
    [Subject("Activity => Capture_Recoveries_Proposal => OnComplete")] // AutoGenerated
    internal class when_capture_recoveries_proposal : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Capture_Recoveries_Proposal(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}