using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.EXT_Under_Cancellation.OnGetStageTransition
{
    [Subject("Activity => EXT_Under_Cancellation => OnGetStageTransition")] // AutoGenerated
    internal class when_ext_under_cancellation : WorkflowSpecDebtCounselling
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_EXT_Under_Cancellation(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}