using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Query_on_Application.OnStart
{
    [Subject("Activity => Query_on_Application => OnStart")] // AutoGenerated
    internal class when_query_on_application : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Query_on_Application(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}