using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Send_Feedback.OnComplete
{
    [Subject("Activity => Send_Feedback => OnComplete")] // AutoGenerated
    internal class when_send_feedback : WorkflowSpecApplicationCapture
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
			string message = string.Empty;
            result = workflow.OnCompleteActivity_Send_Feedback(instanceData, workflowData, paramsData, messages, ref message);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}