using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.Activities.Ready_For_Readvance.OnStart
{
    [Subject("Activity => Ready_For_Readvance => OnStart")] // AutoGenerated
    internal class when_ready_for_readvance : WorkflowSpecCap2
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Ready_For_Readvance(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}