using Machine.Specifications;

namespace WorkflowMaps.ThirdPartyInvoices.Specs.Activities.isLossControlInvoice.OnComplete
{
    [Subject("Activity => isLossControlInvoice => OnComplete")] // AutoGenerated
    internal class when_islosscontrolinvoice : WorkflowSpecThirdPartyInvoices
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
			string message = string.Empty;
            result = workflow.OnCompleteActivity_isLossControlInvoice(instanceData, workflowData, paramsData, messages, ref message);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}