using Machine.Specifications;

namespace WorkflowMaps.ReadvancePayments.Specs.Activities.Archive_Complete_Followup.OnComplete
{
    [Subject("Activity => Archive_Complete_Followup => OnComplete")] // AutoGenerated
    internal class when_archive_complete_followup : WorkflowSpecReadvancePayments
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Archive_Complete_Followup(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}