using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Decline_By_Credit_Timer.OnStart
{
    [Subject("Activity => Decline_By_Credit_Timer => OnStart")] // AutoGenerated
    internal class when_decline_by_credit_timer : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Decline_By_Credit_Timer(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}