//using Machine.Specifications;

//namespace WorkflowMaps.Credit.Specs.States.Common_Application_Employment_Type_Confirmation.OnEnter
//{
//    [Subject("State => Common_Application_Employment_Type_Confirmation => OnEnter")] // AutoGenerated
//    internal class when_common_application_employment_type_confirmation : WorkflowSpecCredit
//    {
//        static bool result;
//        Establish context = () =>
//        {
//            result = false;
//        };
		
//        Because of = () =>
//        {
//            result = workflow.OnEnter_Common_Application_Employment_Type_Confirmation(messages, workflowData, instanceData, paramsData);
//        };

//        It should_return_true = () =>
//        {
//            result.ShouldBeTrue();
//        };
//    }
//}