using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.States.Termination_.OnEnter
{
    [Subject("State => Termination_ => OnEnter")] // AutoGenerated
    internal class when_termination_ : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Termination_(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}