using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Query_on_Application.OnComplete
{
    [Subject("Activity => Query_on_Application => OnComplete")] // AutoGenerated
    internal class when_query_on_application : WorkflowSpecApplicationManagement
    {
        static bool result;
        Establish context = () =>
        {
            result = true;
        };
		
        Because of = () =>
        {
			string message = string.Empty;
            result = workflow.OnCompleteActivity_Query_on_Application(instanceData, workflowData, paramsData, messages, message);
        };

        It should_return_false = () =>
        {
            result.ShouldBeFalse();
        };
    }
}