//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Common.BusinessModel {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("AccountAttorneyInvoice", Schema="dbo")]
    public partial class AccountAttorneyInvoice : ActiveRecordBase<AccountAttorneyInvoice> {
        
        private int _accountAttorneyInvoiceKey;
        
        private int _accountKey;
        
        private int _attorneyKey;
        
        private string _invoiceNumber;
        
        private decimal _amount;
        
        private string _comment;
        
        [PrimaryKey(PrimaryKeyType.Native, "AccountAttorneyInvoiceKey", ColumnType="Int32")]
        public virtual int AccountAttorneyInvoiceKey {
            get {
                return this._accountAttorneyInvoiceKey;
            }
            set {
                this._accountAttorneyInvoiceKey = value;
            }
        }
        
        [Property("AccountKey", ColumnType="Int32", NotNull=true)]
        public virtual int AccountKey {
            get {
                return this._accountKey;
            }
            set {
                this._accountKey = value;
            }
        }
        
        [Property("AttorneyKey", ColumnType="Int32", NotNull=true)]
        public virtual int AttorneyKey {
            get {
                return this._attorneyKey;
            }
            set {
                this._attorneyKey = value;
            }
        }
        
        [Property("InvoiceNumber", ColumnType="String", NotNull=true)]
        public virtual string InvoiceNumber {
            get {
                return this._invoiceNumber;
            }
            set {
                this._invoiceNumber = value;
            }
        }
        
        [Property("Amount", ColumnType="Decimal", NotNull=true)]
        public virtual decimal Amount {
            get {
                return this._amount;
            }
            set {
                this._amount = value;
            }
        }
        
        [Property("Comment", ColumnType="String")]
        public virtual string Comment {
            get {
                return this._comment;
            }
            set {
                this._comment = value;
            }
        }
    }
    
    public class AccountAttorneyInvoiceHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(AccountAttorneyInvoice)};
        }
    }
}
