//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Common.BusinessModel {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("DebtCounselling", Schema="DebtCounselling")]
    public partial class MigrationDebtCounselling_DAO : ActiveRecordBase<MigrationDebtCounselling_DAO> {
        
        private int _debtCounsellingKey;
        
        private Account _account;
        
        private GeneralStatus _generalStatus;
        
        [Property("DebtCounsellingKey", ColumnType="Int32", NotNull=true)]
        public virtual int DebtCounsellingKey {
            get {
                return this._debtCounsellingKey;
            }
            set {
                this._debtCounsellingKey = value;
            }
        }
        
        [BelongsTo("AccountKey")]
        public virtual Account Account {
            get {
                return this._account;
            }
            set {
                this._account = value;
            }
        }
        
        [BelongsTo("GeneralStatusKey")]
        public virtual GeneralStatus GeneralStatus {
            get {
                return this._generalStatus;
            }
            set {
                this._generalStatus = value;
            }
        }
    }
    
    [ActiveRecord("Account", Schema="dbo")]
    public partial class Account : ActiveRecordBase<Account> {
        
        private int _accountKey;
        
        private double _fixedPayment;
        
        private int _accountStatusKey;
        
        private System.DateTime _insertedDate;
        
        private int _originationSourceProductKey;
        
        private System.DateTime _openDate;
        
        private System.DateTime _closeDate;
        
        private int _rrrProductkey;
        
        private int _rrrOriginationsourcekey;
        
        private string _userID;
        
        private System.DateTime _changeDate;
        
        private IList<MigrationDebtCounselling_DAO> _debtCounsellings;
        
        [Property("AccountKey", ColumnType="Int32", NotNull=true)]
        public virtual int AccountKey {
            get {
                return this._accountKey;
            }
            set {
                this._accountKey = value;
            }
        }
        
        [Property("FixedPayment", ColumnType="Double", NotNull=true)]
        public virtual double FixedPayment {
            get {
                return this._fixedPayment;
            }
            set {
                this._fixedPayment = value;
            }
        }
        
        [Property("AccountStatusKey", ColumnType="Int32", NotNull=true)]
        public virtual int AccountStatusKey {
            get {
                return this._accountStatusKey;
            }
            set {
                this._accountStatusKey = value;
            }
        }
        
        [Property("InsertedDate", ColumnType="Timestamp", NotNull=true)]
        public virtual System.DateTime InsertedDate {
            get {
                return this._insertedDate;
            }
            set {
                this._insertedDate = value;
            }
        }
        
        [Property("OriginationSourceProductKey", ColumnType="Int32")]
        public virtual int OriginationSourceProductKey {
            get {
                return this._originationSourceProductKey;
            }
            set {
                this._originationSourceProductKey = value;
            }
        }
        
        [Property("OpenDate", ColumnType="Timestamp")]
        public virtual System.DateTime OpenDate {
            get {
                return this._openDate;
            }
            set {
                this._openDate = value;
            }
        }
        
        [Property("CloseDate", ColumnType="Timestamp")]
        public virtual System.DateTime CloseDate {
            get {
                return this._closeDate;
            }
            set {
                this._closeDate = value;
            }
        }
        
        [Property("RRR_ProductKey", ColumnType="Int32")]
        public virtual int RrrProductkey {
            get {
                return this._rrrProductkey;
            }
            set {
                this._rrrProductkey = value;
            }
        }
        
        [Property("RRR_OriginationSourceKey", ColumnType="Int32")]
        public virtual int RrrOriginationsourcekey {
            get {
                return this._rrrOriginationsourcekey;
            }
            set {
                this._rrrOriginationsourcekey = value;
            }
        }
        
        [Property("UserID", ColumnType="String")]
        public virtual string UserID {
            get {
                return this._userID;
            }
            set {
                this._userID = value;
            }
        }
        
        [Property("ChangeDate", ColumnType="Timestamp")]
        public virtual System.DateTime ChangeDate {
            get {
                return this._changeDate;
            }
            set {
                this._changeDate = value;
            }
        }
        
        [HasMany(typeof(MigrationDebtCounselling_DAO), ColumnKey="AccountKey", Table="DebtCounselling")]
        public virtual IList<MigrationDebtCounselling_DAO> DebtCounsellings {
            get {
                return this._debtCounsellings;
            }
            set {
                this._debtCounsellings = value;
            }
        }
    }
    
    [ActiveRecord("GeneralStatus", Schema="dbo")]
    public partial class GeneralStatus : ActiveRecordBase<GeneralStatus> {
        
        private int _generalStatusKey;
        
        private string _description;
        
        private IList<MigrationDebtCounselling_DAO> _debtCounsellings;
        
        [PrimaryKey(PrimaryKeyType.Native, "GeneralStatusKey", ColumnType="Int32")]
        public virtual int GeneralStatusKey {
            get {
                return this._generalStatusKey;
            }
            set {
                this._generalStatusKey = value;
            }
        }
        
        [Property("Description", ColumnType="String")]
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        [HasMany(typeof(MigrationDebtCounselling_DAO), ColumnKey="GeneralStatusKey", Table="DebtCounselling")]
        public virtual IList<MigrationDebtCounselling_DAO> DebtCounsellings {
            get {
                return this._debtCounsellings;
            }
            set {
                this._debtCounsellings = value;
            }
        }
    }
    
    public class DebtCounsellingHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(MigrationDebtCounselling_DAO),
                    typeof(Account),
                    typeof(GeneralStatus)};
        }
    }
}
