//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Common.BusinessModel.ActiveWriter {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("Feature", Schema="dbo")]
    public partial class Feature : ActiveRecordBase<Feature> {
        
        private string _shortName;
        
        private string _longName;
        
        private bool _hasAccess;
        
        private int _sequence;
        
        private int _featureKey;
        
        private IList<Feature> _features;
        
        private Feature _feature;
        
        [Property("ShortName", ColumnType="String", NotNull=true)]
        public virtual string ShortName {
            get {
                return this._shortName;
            }
            set {
                this._shortName = value;
            }
        }
        
        [Property("LongName", ColumnType="String", NotNull=true)]
        public virtual string LongName {
            get {
                return this._longName;
            }
            set {
                this._longName = value;
            }
        }
        
        [Property("HasAccess", ColumnType="Boolean", NotNull=true)]
        public virtual bool HasAccess {
            get {
                return this._hasAccess;
            }
            set {
                this._hasAccess = value;
            }
        }
        
        [Property("Sequence", ColumnType="Int32", NotNull=true)]
        public virtual int Sequence {
            get {
                return this._sequence;
            }
            set {
                this._sequence = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "FeatureKey", ColumnType="Int32")]
        public virtual int FeatureKey {
            get {
                return this._featureKey;
            }
            set {
                this._featureKey = value;
            }
        }
        
        [HasMany(typeof(Feature), ColumnKey="ParentKey", Table="Feature")]
        public virtual IList<Feature> Features {
            get {
                return this._features;
            }
            set {
                this._features = value;
            }
        }
        
        [BelongsTo("ParentKey", NotNull=false)]
        public virtual Feature Feature {
            get {
                return this._feature;
            }
            set {
                this._feature = value;
            }
        }
    }
}
