//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Common.BusinessModel {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord("PopulationGroup", Schema="dbo")]
    public partial class PopulationGroup : ActiveRecordBase<PopulationGroup> {
        
        private string _description;
        
        private int _populationGroupKey;
        
        [Property("Description", ColumnType="String", NotNull=true)]
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        [PrimaryKey(PrimaryKeyType.Native, "PopulationGroupKey", ColumnType="Int32")]
        public virtual int PopulationGroupKey {
            get {
                return this._populationGroupKey;
            }
            set {
                this._populationGroupKey = value;
            }
        }
    }
}
