namespace SAHL.Core.BusinessModel.Enums
{
    public enum DisabilityType
    {
        AlzheimersDisease = 1,
        Arthritis_Osteo_Rheumatoid = 2,
        BackCondition = 3,
        BenignTumours = 4,
        Blindness = 5,
        Cancer = 6,
        Cardiac_CABG_STENT = 7,
        Cardiac_HeartAttack = 8,
        Cardiac_HeartFailure = 9,
        CVA_Stroke = 10,
        Depression_PTSD = 11,
        DiabetesMellitusRelated = 12,
        FailedBackSyndrome = 13,
        Fractureoflimbs = 14,
        HeadInjury = 15,
        HipReplacement = 16,
        Musculoskeletal_knee_shoulderinjuries = 17,
        Other = 18,
        Paraplegia_Quadriplegia = 19,
        ParkinsonsDisease = 20,
        PeripheralVascularDisease_DVT = 21,
        RenalFailure_DiabMel = 22,
        RenalFailure_Other = 23,
        Respiratory_Asthma_COPD = 24,
        Respiratory_TB = 25,
        SystemicLupusErythmatosis = 26,
        Epilepsy = 27,
        Amputation = 28,
        Deafness = 29,
        Musculoskeletal = 30,
        Cardiac_other = 31,
        Gastrointestinal = 32,
        Eyes_Cataracts_visionloss = 33,
        LiverCirrhosis = 34,
        Burns = 35,
        RetroviralDisease = 36,
        BloodDisorders = 37
    }
}