namespace SAHL.Core.BusinessModel.Enums
{
    public enum GenericKeyType
    {
        Account = 1,
        Offer = 2,
        LegalEntity = 3,
        FinancialService = 4,
        OfferInformation = 5,
        Property = 6,
        Memo = 9,
        Losscontrol = 12,
        DebtCounselling = 15,
        Dispute = 16,
        CapOffer = 17,
        WorkflowCase = 18,
        ParentAccount = 19,
        RelatedLegalEntity = 20,
        Valuation = 21,
        SPV = 22,
        SPVTrancheDefinition = 23,
        Trade = 24,
        OfferRoleTypeOrganisationStructureMapping = 25,
        StageDefinitionStageDefinitionGroup = 26,
        DebtCounselling2AM = 27,
        Proposal = 28,
        DebitOrderBatch = 29,
        FinancialTransactionKey = 30,
        ArrearTransactionKey = 31,
        SPVTransactionKey = 32,
        OfferRoleType = 33,
        WorkflowRoleType = 34,
        Attorney = 35,
        FinancialServiceType = 36,
        FeeType = 37,
        FinancialAdjustmentKey = 38,
        WorkflowRoleTypeOrganisationStructureMapping = 39,
        CreditUnsecuredLendingKey = 40,
        ExternalRoleType = 41,
        Employment = 42,
        Employer = 43,
        Address = 44,
        LegalEntityBankAccount = 45,
        LegalEntityAddress = 46,
        OfferMailingAddress = 47,
        StageTransitionComposite = 48,
        LegalEntityAssetLiability = 49,
        OfferDebitOrder = 50,
        OfferRole = 51,
        ComcorpOfferPropertyDetails = 53,
        ThirdPartyInvoice = 54,
        DisabilityClaim = 55,
        AffordabilityAssessment = 58,
        ThirdParty = 56,
        Valuator = 59,
        CATSPaymentBatch = 60
    }
}