namespace SAHL.Core.BusinessModel.Enums
{
    public enum ReasonType
    {
        AdministrativeDecline = 3,
        ApplicationNTU = 11,
        QuickCashNTU = 12,
        QuickCashDecline = 13,
        CreditDecline = 14,
        LifePolicyCancellation = 15,
        LifeCallback = 16,
        LifeNTU = 17,
        ProcessorQuery = 18,
        RevisionCreditDecline = 19,
        RevisionInitial = 20,
        RevisionReSubmission = 21,
        QAQuery = 22,
        QAComplete = 23,
        CapCancellation = 24,
        Resubmission = 25,
        DebtConsolidation = 26,
        MovableAssetsFinance = 27,
        HomeRenovation = 28,
        InvestmentProperty = 29,
        NewHomePurchase = 30,
        ChangeFinancialInstitution = 31,
        LeadNTU = 32,
        PipelineNTU = 33,
        OriginationNTU = 34,
        BranchDecline = 35,
        CreditScoringDecline = 36,
        CreditScoringQuery = 37,
        LifeProductSwitch = 38,
        LitigationReallocation = 40,
        ProposalAccepted = 41,
        DebtCounsellingTermination = 42,
        ProposalDeclined = 43,
        DebtCounsellingCancelled = 44,
        AccountClose = 45,
        CounterProposals = 46,
        DebtCounsellingNotification = 47,
        ConsultantDeclined = 48,
        PersonalLoanDecline = 49,
        NTUPersonalLoan = 50,
        RequestPhysicalValuation = 51,
        PersonalLoanAdminDecline = 52,
        ContactwithClient = 53,
        CapitecBranchDecline = 54,
        DisabilityClaimRepudiate = 55,
        DisabilityClaimTerminate = 56,
        CreditDisqualify30YearTerm = 57
    }
}