using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.Note.OnStart
{
    [Subject("Activity => Note => OnStart")] // AutoGenerated
    internal class when_note : WorkflowSpecValuations
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Note(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}