using Machine.Specifications;

namespace WorkflowMaps.Life.Specs.Activities.Accept_FAIS.OnComplete
{
    [Subject("Activity => Accept_FAIS => OnComplete")] // AutoGenerated
    internal class when_accept_fais : WorkflowSpecLife
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Accept_FAIS(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}