using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Common_Assign_Admin.OnEnter
{
    [Subject("State => Common_Assign_Admin => OnEnter")] // AutoGenerated
    internal class when_common_assign_admin : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Assign_Admin(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}