using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Credit_Hold.OnExit
{
    [Subject("State => Credit_Hold => OnExit")] // AutoGenerated
    internal class when_credit_hold : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnExit_Credit_Hold(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}