using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Readvance_Payment.OnComplete
{
    [Subject("Activity => Readvance_Payment => OnComplete")] // AutoGenerated
    internal class when_readvance_payment : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Readvance_Payment(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}