using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Attorney_Check.OnEnter
{
    [Subject("State => Attorney_Check => OnEnter")] // AutoGenerated
    internal class when_attorney_check : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Attorney_Check(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}