using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Send_Intent_to_Terminate.OnComplete
{
    [Subject("Activity => Send_Intent_to_Terminate => OnComplete")] // AutoGenerated
    internal class when_send_intent_to_terminate : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Send_Intent_to_Terminate(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}