using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Ready_To_Followup.OnExit
{
    [Subject("State => Ready_To_Followup => OnExit")] // AutoGenerated
    internal class when_ready_to_followup : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnExit_Ready_To_Followup(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}