USE [2AM]
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ThirdPartyInvoice' AND COLUMN_NAME = 'InvoiceStatusKey')
BEGIN
	ALTER TABLE [2AM].dbo.ThirdPartyInvoice
	ADD InvoiceStatusKey INT NOT NULL DEFAULT 1 REFERENCES [2AM].dbo.InvoiceStatus(InvoiceStatusKey)
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ThirdPartyInvoice' AND COLUMN_NAME = 'AccountKey')
BEGIN
	ALTER TABLE [2AM].dbo.ThirdPartyInvoice
	ADD AccountKey INT NOT NULL REFERENCES [2AM].dbo.Account(AccountKey)
END