using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.States.Common_Negotiate_Proposal.OnEnter
{
    [Subject("State => Common_Negotiate_Proposal => OnEnter")] // AutoGenerated
    internal class when_common_negotiate_proposal : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Negotiate_Proposal(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}