using Machine.Specifications;
using System;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities._90_day_timer.OnGetActivityTime
{
    [Subject("Activity => 90_day_timer => OnGetActivityTime")] // AutoGenerated
    internal class when_90_day_timer : WorkflowSpecApplicationCapture
    {
        private static DateTime expectedDateTime;
        private static DateTime result;

        private Establish context = () =>
        {
            expectedDateTime = DateTime.Now.AddDays(90);
            result = default(DateTime);
        };

        private Because of = () =>
        {
            result = workflow.GetActivityTime_90_day_timer(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_datetime_90_days_from_now = () =>
        {
            result.Date.ShouldEqual<DateTime>(expectedDateTime.Date);
        };
    }
}