// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SAHL.Tools.Workflow.Common.Templates
{
    using SAHL.Tools.Workflow.Common.WorkflowElements;
    using System.Data;
    using System.Data.SqlClient;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class X2ProcessLegacy : X2ProcessLegacyBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.IO;\r\nusing System.Reflection;\r\nusing SAHL.Core.Logging;\r\nusing SAHL." +
                    "Core.X2.Logging;\r\nusing StructureMap;\r\n");
            
            #line 10 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
 foreach(UsingStatement usingStatement in process.UsingStatements)
{ 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 12 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(usingStatement.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 13 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 14 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(process.SafeName));
            
            #line default
            #line hidden
            this.Write(@"
{

	#region Process

	public class Process : MarshalByRefObject, IX2LegacyProcess
	{
		SAHL.Core.X2.Logging.IX2Logging x2logger;
		SAHL.Core.Logging.ILogger logger;
		SAHL.Core.Logging.ILoggerSource loggerSource;

		public Process()
		{
		    this.logger=ObjectFactory.GetInstance<SAHL.Core.Logging.ILogger>();
			this.x2logger=ObjectFactory.GetInstance<SAHL.Core.X2.Logging.IX2Logging>();
			this.loggerSource=ObjectFactory.GetInstance<SAHL.Core.Logging.ILoggerSource>();
            var uiStatementProvider = this.GetUIStatementProvider();
			DbContextConfiguration.Instance.RepositoryFactory.UIStatementProvider.Add(uiStatementProvider);
		}
		
		public void ClearCache(ISystemMessageCollection messages, Object data)
		{
			try
			{
				ICommon client = DomainServiceLoader.Instance.Get<ICommon>();
				client.ClearCache((IDomainMessageCollection)messages, data);
			}
			catch(Exception exception)
			{
				x2logger.LogOnWorkflowException(""ClearCache"", 0, exception);
			}
		}
		
		public IUIStatementsProvider GetUIStatementProvider()
		{
			return new UIStatements();
		}

		public override object InitializeLifetimeService()
		{
			return null;
		}
		
		public IX2Map GetWorkflowMap(string WorkFlowName)
		{
			switch(WorkFlowName)
			{
");
            
            #line 61 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
 foreach(Workflow workflow in process.Workflows)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 63 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn new X2");
            
            #line 64 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 65 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\tdefault:\r\n\t\t\t\t\treturn null;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tpublic string GetDynamicRole(st" +
                    "ring RoleName)\r\n\t\t{\r\n\t\t\tswitch(RoleName)\r\n\t\t\t{\r\n");
            
            #line 75 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(GlobalRole role in process.DynamicGlobalRoles)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 77 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(role.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnGetRole_");
            
            #line 78 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(role.SafeName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 79 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\tdefault:\r\n\t\t\t\t\treturn null;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\t#region Process Roles\r\n\r\n");
            
            #line 87 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(GlobalRole role in process.DynamicGlobalRoles){
foreach(CodeSection codeSection	in role.AllCodeSections)
{
string[] codeLines = codeSection.Code.Split(new String[]{"\n"}, StringSplitOptions.RemoveEmptyEntries);
            
            #line default
            #line hidden
            
            #line 91 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(string line in codeLines){
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 92 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 92 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}}
            
            #line default
            #line hidden
            
            #line 93 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\t}\r\n\t\r\n\t#endregion\r\n");
            
            #line 99 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
 foreach(Workflow workflow in process.Workflows){
            
            #line default
            #line hidden
            this.Write("\t\r\n\t#region WorkFlowData ");
            
            #line 100 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n\tpublic interface IX2");
            
            #line 102 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data : IX2ContextualDataProvider\r\n\t{\r\n");
            
            #line 104 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractCustomVariable customVariable in workflow.CustomVariables)
{
            
            #line default
            #line hidden
            
            #line 106 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"

	        string typeName = "";
            string typeDeclaration = "";
	        switch(customVariable.VariableType)
            {
                case CustomVariableTypeEnum.Bool:
                    typeName = "Boolean";
                    break;
                case CustomVariableTypeEnum.BigInteger:
                    typeName = "Int64";
                    break;
                case CustomVariableTypeEnum.DateTime:
                    typeName = "DateTime";
                    break;
                case CustomVariableTypeEnum.Decimal:
                    typeName = "Decimal";
                    break;
                case CustomVariableTypeEnum.Double:
                    typeName = "Double";
                    break;
                case CustomVariableTypeEnum.Integer:
                    typeName = "Int32";
                    break;
                case CustomVariableTypeEnum.Single:
                    typeName = "Single";
                    break;
                case CustomVariableTypeEnum.String:
                    typeName = "String";
                    break;
                case CustomVariableTypeEnum.Text:
                    typeName = "String";
                    break;
            }

            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t");
            
            #line 140 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 140 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 141 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\r\n\t}\r\n\t\r\n\tpublic partial class UIStatements : IUIStatementsProvider\r\n    {\r\n\t\tpu" +
                    "blic const string x2");
            
            #line 147 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("_data_insert = \"insert into x2.x2data.");
            
            #line 147 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(" (InstanceID) values (@InstanceID)\";\r\n\t\tpublic const string x2");
            
            #line 148 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("_data_update = \"update x2.x2data.");
            
            #line 148 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(" set ");
            
            #line 148 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
string updateset = "";
			foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) 
			{
				updateset = string.Format("{0}[{1}]=@{1},", updateset, customVariable.SafeName);
			}
			updateset=updateset.Remove(updateset.Length-1,1);
            
            #line default
            #line hidden
            
            #line 153 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(updateset));
            
            #line default
            #line hidden
            this.Write(" where InstanceID=@InstanceID\";\r\n\t\t\r\n\t}\r\n\r\n\tpublic class X2");
            
            #line 157 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("SqlStatement : ISqlStatement<X2");
            
            #line 157 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data>\r\n\t{\r\n\t");
            
            #line 159 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
string s = "";
	foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) {
            
            #line default
            #line hidden
            
            #line 160 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
string typeName = "";
            string typeDeclaration = "";
	        switch(customVariable.VariableType)
            {
                case CustomVariableTypeEnum.Bool:
                    typeName = "Boolean";
                    break;
                case CustomVariableTypeEnum.BigInteger:
                    typeName = "Int64";
                    break;
                case CustomVariableTypeEnum.DateTime:
                    typeName = "DateTime";
                    break;
                case CustomVariableTypeEnum.Decimal:
                    typeName = "Decimal";
                    break;
                case CustomVariableTypeEnum.Double:
                    typeName = "Double";
                    break;
                case CustomVariableTypeEnum.Integer:
                    typeName = "Int32";
                    break;
                case CustomVariableTypeEnum.Single:
                    typeName = "Single";
                    break;
                case CustomVariableTypeEnum.String:
                    typeName = "String";
                    break;
                case CustomVariableTypeEnum.Text:
                    typeName = "String";
                    break;
            }s=s.TrimStart();s+=typeName+" "+customVariable.SafeName+",";
            
            #line default
            #line hidden
            
            #line 191 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("public X2");
            
            #line 191 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("SqlStatement(long instanceId, ");
            
            #line 191 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(s.Remove(s.Length-1,1).TrimStart().TrimEnd()));
            
            #line default
            #line hidden
            this.Write(") \r\n\t\t{\r\n\t\t\tthis.InstanceID=instanceId;\r\n\t");
            
            #line 194 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) {
            
            #line default
            #line hidden
            this.Write("\t\tthis.");
            
            #line 195 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write("=");
            
            #line 195 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 196 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic long InstanceID{get;set;}\r\n\t\t");
            
            #line 200 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) {
            
            #line default
            #line hidden
            
            #line 201 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"

            string typeName = "";
            string typeDeclaration = "";
	        switch(customVariable.VariableType)
            {
                case CustomVariableTypeEnum.Bool:
                    typeName = "Boolean";
                    break;
                case CustomVariableTypeEnum.BigInteger:
                    typeName = "Int64";
                    break;
                case CustomVariableTypeEnum.DateTime:
                    typeName = "DateTime";
                    break;
                case CustomVariableTypeEnum.Decimal:
                    typeName = "Decimal";
                    break;
                case CustomVariableTypeEnum.Double:
                    typeName = "Double";
                    break;
                case CustomVariableTypeEnum.Integer:
                    typeName = "Int32";
                    break;
                case CustomVariableTypeEnum.Single:
                    typeName = "Single";
                    break;
                case CustomVariableTypeEnum.String:
                    typeName = "String";
                    break;
                case CustomVariableTypeEnum.Text:
                    typeName = "String";
                    break;
            }

            
            #line default
            #line hidden
            this.Write("public ");
            
            #line 234 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 234 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write("{get;set;}\r\n");
            
            #line 235 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic string GetStatement()\r\n\t\t{\r\n\t\t\t");
            
            #line 239 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
string SQL = "select InstanceId, ";
			foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) 
			{
				SQL = string.Format("{0} {1},", SQL, customVariable.SafeName);
			}
			SQL=SQL.Remove(SQL.Length-1,1);
			
            
            #line default
            #line hidden
            this.Write("string sql = \"");
            
            #line 245 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SQL));
            
            #line default
            #line hidden
            this.Write(" from x2.x2data.");
            
            #line 245 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(" where instanceId=@InstanceID\";\r\n\t\t\treturn sql;\r\n\t\t}\r\n\t}\r\n\r\n\r\n\tpublic class X2");
            
            #line 251 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data : MarshalByRefObject, IX2");
            
            #line 251 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data\r\n\t{\r\n\t\tprivate bool m_HasChanges = false;\r\n\t\tprivate Dictionary<string, str" +
                    "ing> m_dataFields;\r\n\t\tpublic long InstanceId{get; protected set;}\r\n\t\tpublic X2");
            
            #line 256 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data()\r\n\t\t{\r\n\t\t\tDbContextConfiguration.Instance.RepositoryFactory.UIStatementPro" +
                    "vider.Add(new UIStatements());\r\n\t\t}\r\n\r\n\t\tpublic X2");
            
            #line 261 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data(long instanceId):this()\r\n\t\t{\r\n\t\t\tthis.InstanceId=instanceId;\r\n\t\t\tthis.m_dat" +
                    "aFields = new Dictionary<string, string>();\r\n");
            
            #line 265 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.m_dataFields.Add(\"");
            
            #line 266 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 266 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SqlDataTypeFromCustomVariableType(customVariable.VariableType)));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 267 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t}\r\n\t\t\r\n\t\tpublic override object InitializeLifetimeService()\r\n\t\t{\r\n\t\t\tretur" +
                    "n null;\r\n\t\t}\r\n");
            
            #line 274 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        foreach(AbstractCustomVariable customVariable in workflow.CustomVariables)
        {
            
            #line default
            #line hidden
            
            #line 276 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"

            string typeName = "";
            string typeDeclaration = "";
	        switch(customVariable.VariableType)
            {
                case CustomVariableTypeEnum.Bool:
                    typeName = "Boolean";
                    break;
                case CustomVariableTypeEnum.BigInteger:
                    typeName = "Int64";
                    break;
                case CustomVariableTypeEnum.DateTime:
                    typeName = "DateTime";
                    break;
                case CustomVariableTypeEnum.Decimal:
                    typeName = "Decimal";
                    break;
                case CustomVariableTypeEnum.Double:
                    typeName = "Double";
                    break;
                case CustomVariableTypeEnum.Integer:
                    typeName = "Int32";
                    break;
                case CustomVariableTypeEnum.Single:
                    typeName = "Single";
                    break;
                case CustomVariableTypeEnum.String:
                    typeName = "String";
                    break;
                case CustomVariableTypeEnum.Text:
                    typeName = "String";
                    break;
            }

            
            #line default
            #line hidden
            this.Write("\t\r\n");
            
            #line 310 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            if(customVariable.VariableType == CustomVariableTypeEnum.DateTime){
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 311 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write(" m_");
            
            #line 311 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" = System.DateTime.Now;\r\n");
            
            #line 312 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            }else{
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 313 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write(" m_");
            
            #line 313 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 314 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            }
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 315 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 315 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn m_");
            
            #line 319 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tm_HasChanges = true;\r\n\t\t\t\tm_");
            
            #line 324 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 327 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        }
            
            #line default
            #line hidden
            this.Write("\t\r\n\t\t#region IX2WorkFlowDataProvider Members\r\n\r\n\t\tpublic void LoadData(long insta" +
                    "nceId)\r\n\t\t{\r\n\t\t\tusing (var db = new Db().InWorkflowContext())\r\n            {\r\n\t\t" +
                    "\t    var workflowData = db.SelectOne<X2");
            
            #line 335 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data>(new X2");
            
            #line 335 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("SqlStatement(instanceId,");
            
            #line 335 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
string sql = "";
			foreach(AbstractCustomVariable customVariable in workflow.CustomVariables) 
			{
				sql = string.Format("{0} {1},", sql, customVariable.SafeName);
			}
			sql=sql.Remove(sql.Length-1,1);
            
            #line default
            #line hidden
            
            #line 340 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sql));
            
            #line default
            #line hidden
            this.Write(@"));
				SetProperties(workflowData);
				db.Complete();
            }
		}

		public void InsertData(long instanceId, System.Collections.Generic.Dictionary<string, string> Fields)
		{
			using (var db = new Db().InWorkflowContext())
            {
				SetMapVariables(Fields);
				db.Insert<X2");
            
            #line 351 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data>(this);\r\n\t\t\t\tdb.Complete();\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic void SaveData(long insta" +
                    "nceId)\r\n\t\t{\r\n\t\t\tusing (var db = new Db().InWorkflowContext())\r\n            {\r\n\t\t" +
                    "\t\tdb.Update<X2");
            
            #line 360 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@"_Data>(this);
				db.Complete();
			}
		}

		public void SetMapVariables(System.Collections.Generic.Dictionary<string, string> Fields)
		{
			if (Fields != null)
			{
				string[] Keys = new string[Fields.Count];
				Fields.Keys.CopyTo(Keys, 0);
				for (int i = 0; i < Fields.Count; i++)
				{
					switch (Keys[i].ToLower())
					{
");
            
            #line 375 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tcase \"");
            
            #line 376 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\t\t\t");
            
            #line 377 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" = Convert.");
            
            #line 377 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConvertStringFromCustomVariableType(customVariable.VariableType)));
            
            #line default
            #line hidden
            this.Write("(Fields[Keys[i]]);\r\n\t\t\t\t\t\t\tbreak;\r\n");
            
            #line 379 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        }
            
            #line default
            #line hidden
            this.Write(@"					}
				}
			}
		}

		public void SetProperties(object setPropertiesFromObject)
           {
                foreach (var property in setPropertiesFromObject.GetType().GetProperties())
                {
                     var propertyToSet = this.GetType().GetProperty(property.Name);
					 if (property.Name != ""DataFields"" && propertyToSet.SetMethod != null)
					 {
						 if (propertyToSet != null)
						 {
							   propertyToSet.SetValue(this, property.GetValue(setPropertiesFromObject));
						 }
					}
                }
           }

		public Dictionary<string, string> GetData()
		{
			Dictionary<string, string> Data = new Dictionary<string, string>();
");
            
            #line 403 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            
            #line 404 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
if(this.RequiresNullCheck(customVariable.VariableType)){
            
            #line default
            #line hidden
            this.Write("\t\t\tif(m_");
            
            #line 405 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t\tData.Add( \"");
            
            #line 406 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\", m_");
            
            #line 406 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(".ToString());\r\n");
            
            #line 407 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\tData.Add( \"");
            
            #line 408 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\", m_");
            
            #line 408 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(".ToString());\r\n");
            
            #line 409 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            
            #line 410 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\treturn Data;\r\n\t\t}\r\n\t\t\r\n\t\tpublic void SetDataField(string FieldName, object val" +
                    "ue)\r\n\t\t{\r\n\t\t\tswitch (FieldName.ToLower())\r\n\t\t\t{\t\t\r\n");
            
            #line 418 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tcase \"");
            
            #line 419 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\t\t\t");
            
            #line 420 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(" = Convert.");
            
            #line 420 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConvertStringFromCustomVariableType(customVariable.VariableType)));
            
            #line default
            #line hidden
            this.Write("(value);\r\n\t\t\t\t\t\t\tbreak;\r\n");
            
            #line 422 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        }
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tpublic object GetDataField(string FieldName)\r\n\t\t{\r\n\t\t\tswitch (Fi" +
                    "eldName.ToLower())\r\n\t\t\t{\r\n");
            
            #line 430 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 431 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn m_");
            
            #line 432 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 433 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t\tdefault:\r\n\t\t\t\t\treturn null;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tpublic Dictionary<string, " +
                    "string> DataFields\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn m_dataFields;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n" +
                    "\t\tpublic string DataProviderName\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn \"");
            
            #line 451 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tpublic bool HasChanges\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn m_HasC" +
                    "hanges;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tpublic bool Contains(string FieldName)\r\n\t\t{\r\n\t\t\tswitch" +
                    " (FieldName.ToLower())\r\n\t\t\t{\r\n");
            
            #line 467 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
        foreach(AbstractCustomVariable customVariable in workflow.CustomVariables){
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 468 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customVariable.SafeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn true;\r\n");
            
            #line 470 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\r\n\t\t\t\tdefault:\r\n\t\t\t\t\treturn false;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\r\n\r\n\t#endregion\r\n}\r\n\r\n\t#end" +
                    "region\t\r\n\r\n\t#region WorkFlow ");
            
            #line 483 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\tpublic class X2");
            
            #line 485 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(" : MarshalByRefObject, IX2Map\r\n\t{\r\n\t\tSAHL.Core.X2.Logging.IX2Logging x2logger;\r\n\t" +
                    "\tSAHL.Core.Logging.ILogger logger;\r\n\t\tSAHL.Core.Logging.ILoggerSource loggerSour" +
                    "ce;\r\n\t\t\r\n\t\tpublic X2");
            
            #line 491 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@"()
		{
		    this.logger=ObjectFactory.GetInstance<SAHL.Core.Logging.ILogger>();
			this.x2logger=ObjectFactory.GetInstance<SAHL.Core.X2.Logging.IX2Logging>();
			this.loggerSource=ObjectFactory.GetInstance<SAHL.Core.Logging.ILoggerSource>();
		}
		
		#region States
");
            
            #line 499 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractNamedState state in workflow.States){
foreach(CodeSection codeSection	in state.AllCodeSections)
{
string[] codeLines = codeSection.Code.Split(new String[]{"\r\n"}, StringSplitOptions.RemoveEmptyEntries);
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 504 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(string line in codeLines){
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 505 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 505 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("\r\n"));
            
            #line default
            #line hidden
            
            #line 505 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}}
            
            #line default
            #line hidden
            
            #line 506 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\r\n\t\t#region Activities\r\n");
            
            #line 511 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractActivity activity in workflow.Activities){
foreach(CodeSection codeSection	in activity.AllCodeSections)
{
string[] codeLines = codeSection.Code.Split(new String[]{"\r\n"}, StringSplitOptions.RemoveEmptyEntries);
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 516 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(string line in codeLines){
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 517 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 517 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("\r\n"));
            
            #line default
            #line hidden
            
            #line 517 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}}
            
            #line default
            #line hidden
            
            #line 518 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t#endregion\r\n\r\n\t\t#region Roles\r\n");
            
            #line 523 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"

foreach(AbstractRole role in workflow.Roles){
foreach(CodeSection codeSection	in role.AllCodeSections)
{
string[] codeLines = codeSection.Code.Split(new String[]{"\r\n"}, StringSplitOptions.RemoveEmptyEntries);
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 529 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(string line in codeLines){
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 530 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 530 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("\r\n"));
            
            #line default
            #line hidden
            
            #line 530 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}}
            
            #line default
            #line hidden
            
            #line 531 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
		#endregion

		#region IX2Map Members

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool EnterState(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<bool> internalMethod = () =>
				{
					return this.OnEnterStateInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 547 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""OnEnterState"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""OnEnterState"",metricParameters);
				return returnData;
			}
            catch (DomainMessageException dme)
            {
                return false;
            }
            catch (DomainValidationException dve)
            {
                return false;
            }
			catch(Exception exception)
			{
				if (messages.AllMessages.Count() == 0)
                {
					x2logger.LogOnWorkflowException(""OnEnterState"", instance.ID, exception);
					throw new Exception(""A serious internal error has occurred and workflow processing was aborted."");
                }
				return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnEnterStateInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.StateName)
			{
");
            
            #line 576 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractNamedState state in workflow.States)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 578 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnEnter_");
            
            #line 579 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 579 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 580 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"					
				default:
					return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool ExitState(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<bool>  internalMethod = () =>
				{
					return this.OnExitStateInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 596 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""OnExitState"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""OnExitState"",metricParameters);
				return returnData;
			}
            catch (DomainMessageException dme)
            {
                return false;
            }
            catch (DomainValidationException dve)
            {
                return false;
            }
			catch(Exception exception)
			{
				
				if (messages.AllMessages.Count() == 0)
                {
					x2logger.LogOnWorkflowException( ""OnExitState"", instance.ID, exception);
					throw new Exception(""A serious internal error has occurred and workflow processing was aborted."");
                }
				return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnExitStateInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.StateName)
			{
");
            
            #line 626 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractNamedState state in workflow.States)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 628 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnExit_");
            
            #line 629 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 629 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 630 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"								
				default:
					return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnReturnState(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<bool> internalMethod = () =>
				{
					return this.OnReturnStateInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 646 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""OnReturnState"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""OnReturnState"",metricParameters);
				return returnData;
			}
            catch (DomainMessageException dme)
            {
                return false;
            }
            catch (DomainValidationException dve)
            {
                return false;
            }
			catch(Exception exception)
			{
				if (messages.AllMessages.Count() == 0)
				{
					x2logger.LogOnWorkflowException( ""OnReturnState"", instance.ID, exception);
					throw new Exception(""A serious internal error has occurred and workflow processing was aborted."");
				}
				return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnReturnStateInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.StateName)
			{
");
            
            #line 675 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(ArchiveState state in workflow.ArchiveStates)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 677 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnReturn_");
            
            #line 678 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance,(IX2");
            
            #line 678 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 679 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"	
					default: 
						return false;
				}
			}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetForwardStateName(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<string> internalMethod = () =>
				{
					return this.GetForwardStateNameInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 695 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""GetForwardStateName"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""GetForwardStateName"",metricParameters);
				return returnData;
			}
			catch(Exception exception)
			{
				return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetForwardStateNameInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.StateName)
			{
");
            
            #line 711 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(SystemState state in workflow.AutoForwardStates)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 713 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn GetForwardStateName_");
            
            #line 714 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(state.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 714 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 715 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"				
				default:
					return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool StartActivity(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{

				Func<bool> internalMethod = () =>
				{
					return this.OnStartActivityInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 732 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""OnStartActivity"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""OnStartActivity"",metricParameters);
				return returnData;
			}
            catch (DomainMessageException dme)
            {
                return false;
            }
            catch (DomainValidationException dve)
            {
                return false;
            }
			catch(Exception exception)
			{
				if (messages.AllMessages.Count() == 0)
                {
					x2logger.LogOnWorkflowException( ""OnStartActivity"", instance.ID, exception);
					throw new Exception(""A serious internal error has occurred and workflow processing was aborted."");
                }
				return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnStartActivityInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.ActivityName)
			{
");
            
            #line 761 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractActivity activity in workflow.Activities)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 763 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnStartActivity_");
            
            #line 764 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 764 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 765 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"				
				default:
					return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool CompleteActivity(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages, ref string AlertMessage)
		{
			try
			{
				logger.GetThreadLocalStore()[SAHL.Core.Logging.Logger.X2InstanceId] = instance.ID;
                logger.GetThreadLocalStore()[SAHL.Core.Logging.Logger.X2WorkflowName] = param.WorkflowName;
                logger.GetThreadLocalStore()[SAHL.Core.Logging.Logger.X2InstanceData] = param;
                logger.GetThreadLocalStore()[SAHL.Core.Logging.Logger.X2ActivityName] = param.ActivityName;


				Func<Tuple<bool, string>> internalMethod = () =>
				{
					bool item1 = false;
					string item2 = string.Empty;
					item1 = this.OnCompleteActivityInternal(instance, contextualData, param, messages, ref item2);
					Tuple<bool, string> values = new Tuple<bool,string>(item1,item2);
					return values;
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 791 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param} };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""OnCompleteActivity"",internalMethod, metricParameters);
				if (!string.IsNullOrEmpty(returnData.Item2))
				{
					AlertMessage = returnData.Item2;
				}
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""OnCompleteActivity"",metricParameters);
				return returnData.Item1;
			}
            catch (DomainMessageException dme)
            {
                return false;
            }
            catch (DomainValidationException dve)
            {
                return false;
            }
			catch(Exception exception)
			{
				if (messages.AllMessages.Count() == 0)
                {
					x2logger.LogOnWorkflowException( ""OnCompleteActivity"", instance.ID, exception);
					throw new Exception(""A serious internal error has occurred and workflow processing was aborted."");
                }
				return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public bool OnCompleteActivityInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages, ref string AlertMessage)
		{
			switch(param.ActivityName)
			{
");
            
            #line 824 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractActivity activity in workflow.Activities)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 826 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnCompleteActivity_");
            
            #line 827 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 827 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages, ref AlertMessage);\r\n");
            
            #line 828 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"				
				default:
					return false;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public DateTime GetActivityTime(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				
				Func<DateTime> internalMethod = () =>
				{
					return this.GetActivityTimeInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 845 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""GetActivityTime"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""GetActivityTime"",metricParameters);
				return returnData;
			}
			catch(Exception exception)
			{
				if (messages.AllMessages.Count() == 0)
                {
                    // add an error message to the message collection so that X2 will definately not continue, ONLY if there are not already messages.
                    messages.AddMessage(new SAHL.Core.SystemMessages.SystemMessage(String.Format(""A serious internal error has occurred and workflow processing was aborted.{0}"", exception.ToString()), SAHL.Core.SystemMessages.SystemMessageSeverityEnum.Error));
					x2logger.LogOnWorkflowException( ""GetActivityTime"", instance.ID, exception);
                }
				return DateTime.Now;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public DateTime GetActivityTimeInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.ActivityName)
			{
");
            
            #line 867 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(TimedActivity activity in workflow.TimedActivities)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 869 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn GetActivityTime_");
            
            #line 870 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 870 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 871 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"					
				default:
					return DateTime.Now;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetStageTransition(InstanceDataModel instance, IX2ContextualDataProvider contextualData,SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<string> internalMethod = () =>
				{
					return this.GetStageTransitionInternal(contextualData, instance,  param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 887 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param } };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""GetStageTransition"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""GetStageTransition"",metricParameters);
				return returnData;
			}
			catch(Exception exception)
			{
				return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetStageTransitionInternal(IX2ContextualDataProvider contextualData, InstanceDataModel instance, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.ActivityName)
			{
");
            
            #line 903 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractActivity activity in workflow.ActivitiesWithStageTransitions)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 905 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn GetStageTransition_");
            
            #line 906 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 906 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 907 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"						
				default:
					return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetActivityMessage(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<string> internalMethod = () =>
				{
					return this.GetActivityMessageInternal(instance, contextualData, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 923 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }, { Logger.X2Parameters, param} };
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""GetActivityMessage"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""GetActivityMessage"",metricParameters);
				return returnData;
			}
			catch(Exception exception)
			{
				return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetActivityMessageInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(param.ActivityName)
			{
");
            
            #line 939 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(AbstractActivity activity in workflow.UserActivities)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 941 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn GetActivityMessage_");
            
            #line 942 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activity.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 942 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData, param, messages);\r\n");
            
            #line 943 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write(@"					
				default:
					return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetDynamicRole(InstanceDataModel instance, IX2ContextualDataProvider contextualData, string roleName, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			try
			{
				Func<string> internalMethod = () =>
				{
					return this.GetDynamicRoleInternal(instance, contextualData, roleName, param, messages);
				};

				Dictionary<string, object> metricParameters = new Dictionary<string, object>() { { Logger.X2WorkflowName, """);
            
            #line 959 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write(@""" }, { Logger.X2InstanceData, instance }};
				var returnData = logger.LogMethodMetric(this.loggerSource,""X2MAP"",""GetDynamicRole"",internalMethod, metricParameters);
				logger.LogThroughputMetric(this.loggerSource,""X2MAP"",""GetDynamicRole"",metricParameters);
				return returnData;
			}
			catch(Exception exception)
			{
				return string.Empty;
			}
		}

		[SAHL.Core.Attributes.CoverageExcludeAttribute]
		public string GetDynamicRoleInternal(InstanceDataModel instance, IX2ContextualDataProvider contextualData,  string roleName, SAHL.Core.X2.IX2Params param, ISystemMessageCollection messages)
		{
			switch(roleName.Replace(' ', '_')+""_""+param.WorkflowName.Replace(' ', '_'))
			{
");
            
            #line 975 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
foreach(WorkflowRole role in workflow.DynamicRoles)
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 977 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(role.SafeName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 977 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("\":\r\n\t\t\t\t\treturn OnGetRole_");
            
            #line 978 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 978 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(role.SafeName));
            
            #line default
            #line hidden
            this.Write("(instance, (IX2");
            
            #line 978 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data)contextualData,roleName , param, messages);\r\n");
            
            #line 979 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n\t\t\t\tdefault:\r\n\t\t\t\t\treturn string.Empty;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\t[SAHL.Core.Attribut" +
                    "es.CoverageExcludeAttribute]\r\n\t\tpublic IX2ContextualDataProvider GetContextualDa" +
                    "ta(long instanceId)\r\n\t\t{\r\n\t\t\treturn new X2");
            
            #line 988 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(workflow.SafeName));
            
            #line default
            #line hidden
            this.Write("_Data(instanceId);\r\n\t\t}\r\n\r\n\t\t#endregion\r\n\t}\r\n\r\n\t#endregion\r\n\t\r\n");
            
            #line 996 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
}
            
            #line default
            #line hidden
            this.Write("\tpublic partial class UIStatements : IUIStatementsProvider\r\n    {\r\n\t\tpublic strin" +
                    "g UIStatementContext\r\n\t\t{\r\n\t\t\tget { return \"");
            
            #line 1001 "F:\git\dev\Tools\Workflow\src\SAHL.Tools.Workflow.Common\Templates\X2ProcessLegacy.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(process.SafeName));
            
            #line default
            #line hidden
            this.Write("\";/*Name of the actual process*/ }\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class X2ProcessLegacyBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
