using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Valuation_Resubmission_.OnComplete
{
    [Subject("Activity => Valuation_Resubmission_ => OnComplete")] // AutoGenerated
    internal class when_valuation_resubmission_ : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Valuation_Resubmission_(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}