using Machine.Specifications;

namespace WorkflowMaps.Life.Specs.States.Common_Send_Quote.OnEnter
{
    [Subject("State => Common_Send_Quote => OnEnter")] // AutoGenerated
    internal class when_common_send_quote : WorkflowSpecLife
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Send_Quote(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}