using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.States.Common_Litigation.OnEnter
{
    [Subject("State => Common_Litigation => OnEnter")] // AutoGenerated
    internal class when_common_litigation : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Litigation(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}