using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Common_Relodge.OnEnter
{
    [Subject("State => Common_Relodge => OnEnter")] // AutoGenerated
    internal class when_common_relodge : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Relodge(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}