using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Assign_EstateAgent.OnStart
{
    [Subject("Activity => Assign_EstateAgent => OnStart")] // AutoGenerated
    internal class when_assign_estateagent : WorkflowSpecApplicationCapture
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Assign_EstateAgent(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}