using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.Set_Active_Valuation.OnComplete
{
    [Subject("Activity => Set_Active_Valuation => OnComplete")] // AutoGenerated
    internal class when_set_active_valuation : WorkflowSpecValuations
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Set_Active_Valuation(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}