using Machine.Specifications;
using SAHL.WorkflowMaps.LifeClaims.Specs;

namespace WorkflowMaps.DisabilityClaim.Specs.Activities.EXT_Claim_Settled.OnGetStageTransition
{
    [Subject("Activity => EXT_Claim_Settled => OnGetStageTransition")] // AutoGenerated
    internal class when_ext_claim_settled : WorkflowSpecDisabilityClaim
    {
        static string result;
        Establish context = () =>
        {
            result = "abcd";
        };

        Because of = () =>
        {
            result = workflow.GetStageTransition_EXT_Claim_Settled(instanceData, workflowData, paramsData, messages);
        };

        It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}