using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.RetryAssignTeleConsultant.OnComplete
{
    [Subject("Activity => RetryAssignTeleConsultant => OnComplete")] // AutoGenerated
    internal class when_retryassignteleconsultant : WorkflowSpecApplicationCapture
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
			string message = string.Empty;
            result = workflow.OnCompleteActivity_RetryAssignTeleConsultant(instanceData, workflowData, paramsData, messages, ref message);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}