using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Archive_Completed_Followup.OnStart
{
    [Subject("Activity => Archive_Completed_Followup => OnStart")] // AutoGenerated
    internal class when_archive_completed_followup : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Archive_Completed_Followup(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}