using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.Activities.Clear_Cache.OnGetActivityMessage
{
    [Subject("Activity => Clear_Cache => OnGetActivityMessage")] // AutoGenerated
    internal class when_clear_cache : WorkflowSpecCap2
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Clear_Cache(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}