using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Internet_Application.OnStart
{
    [Subject("Activity => Internet_Application => OnStart")] // AutoGenerated
    internal class when_internet_application_and_lead_type_is_4 : WorkflowSpecApplicationCapture
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
            workflowData.LeadType = 4;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Internet_Application(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}