using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Application_Not_Accepted.OnStart
{
    [Subject("Activity => Application_Not_Accepted => OnStart")] // AutoGenerated
    internal class when_application_not_accepted : WorkflowSpecApplicationCapture
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Application_Not_Accepted(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}