using Machine.Specifications;
using SAHL.WorkflowMaps.LifeClaims.Specs;

namespace WorkflowMaps.DisabilityClaim.Specs.Activities.Capture_Details.OnStart
{
    [Subject("Activity => Capture_Details => OnStart")] // AutoGenerated
    internal class when_capture_details : WorkflowSpecDisabilityClaim
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
            result = workflow.OnStartActivity_Capture_Details(instanceData, workflowData, paramsData, messages);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}