using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Term_expired.OnGetStageTransition
{
    [Subject("Activity => Term_expired => OnGetStageTransition")] // AutoGenerated
    internal class when_term_expired : WorkflowSpecDebtCounselling
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_Term_expired(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}