using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.States.Manual_Archive.OnReturn
{
    [Subject("State => Manual_Archive => OnReturn")] // AutoGenerated
    internal class when_manual_archive : WorkflowSpecValuations
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnReturn_Manual_Archive(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}