using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.EXT_Amended_LS.OnStart
{
    [Subject("Activity => EXT_Amended_LS => OnStart")] // AutoGenerated
    internal class when_ext_amended_ls : WorkflowSpecValuations
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_EXT_Amended_LS(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}