using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.States.Application_Reactivated.OnExit
{
    [Subject("State => Application_Reactivated => OnExit")] // AutoGenerated
    internal class when_application_reactivated : WorkflowSpecApplicationCapture
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnExit_Application_Reactivated(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}