using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.Instruct_Ez_Val_Valuer.OnGetActivityMessage
{
    [Subject("Activity => Instruct_Ez_Val_Valuer => OnGetActivityMessage")] // AutoGenerated
    internal class when_instruct_ez_val_valuer : WorkflowSpecValuations
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Instruct_Ez_Val_Valuer(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}