using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.Activities.Print_Cap_Letter.OnComplete
{
    [Subject("Activity => Print_Cap_Letter => OnComplete")] // AutoGenerated
    internal class when_print_cap_letter : WorkflowSpecCap2
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Print_Cap_Letter(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}