using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Resend_LOA.OnStart
{
    [Subject("Activity => Resend_LOA => OnStart")] // AutoGenerated
    internal class when_resend_loa : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Resend_LOA(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}