using Machine.Specifications;

namespace WorkflowMaps.LoanAdjustments.Specs.Activities.Term_Change_Request.OnComplete
{
    [Subject("Activity => Term_Change_Request => OnComplete")] // AutoGenerated
    internal class when_term_change_request : WorkflowSpecLoanAdjustments
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Term_Change_Request(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}