using Machine.Specifications;

namespace SAHL.WorkflowMaps.ThirdPartyInvoices.Specs.Activities.Accept_Invoice.OnGetActivityMessage
{
    [Subject("Activity => Accept_Invoice => OnGetActivityMessage")] // AutoGenerated
    internal class when_accept_invoice : WorkflowSpecThirdPartyInvoices
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Accept_Invoice(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}