using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Valuations_Review.OnComplete
{
    [Subject("Activity => Valuations_Review => OnComplete")] // AutoGenerated
    internal class when_valuations_review : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Valuations_Review(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}