using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Send_Intent_to_Terminate.OnStart
{
    [Subject("Activity => Send_Intent_to_Terminate => OnStart")] // AutoGenerated
    internal class when_send_intent_to_terminate : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Send_Intent_to_Terminate(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}