using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.Request_Lightstone_Valuation.OnStart
{
    [Subject("Activity => Request_Lightstone_Valuation => OnStart")] // AutoGenerated
    internal class when_request_lightstone_valuation : WorkflowSpecValuations
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Request_Lightstone_Valuation(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}