using Machine.Specifications;

namespace WorkflowMaps.ReadvancePayments.Specs.Activities.Complete_Followup.OnStart
{
    [Subject("Activity => Complete_Followup => OnStart")] // AutoGenerated
    internal class when_complete_followup : WorkflowSpecReadvancePayments
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Complete_Followup(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}