using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Rapid_Readvance.OnComplete
{
    [Subject("Activity => Rapid_Readvance => OnComplete")] // AutoGenerated
    internal class when_rapid_readvance : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Rapid_Readvance(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}