using Machine.Specifications;

namespace SAHL.WorkflowMaps.ThirdPartyInvoices.Specs.States.Accepted_for_Processing.OnEnter
{
    [Subject("State => Accepted_for_Processing => OnEnter")] // AutoGenerated
    internal class when_accepted_for_processing : WorkflowSpecThirdPartyInvoices
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Accepted_for_Processing(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}