using Machine.Specifications;

namespace WorkflowMaps.ReadvancePayments.Specs.States.Archive_FL_SuperLo_OptOut.OnEnter
{
    [Subject("State => Archive_FL_SuperLo_OptOut => OnEnter")] // AutoGenerated
    internal class when_archive_fl_superlo_optout : WorkflowSpecReadvancePayments
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Archive_FL_SuperLo_OptOut(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}