using Machine.Specifications;

namespace WorkflowMaps.Valuations.Specs.Activities.Further_Valuation_Requested.OnGetStageTransition
{
    [Subject("Activity => Further_Valuation_Requested => OnGetStageTransition")] // AutoGenerated
    internal class when_further_valuation_requested : WorkflowSpecValuations
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_Further_Valuation_Requested(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}