using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Change_in_Circumstance.OnGetStageTransition
{
    [Subject("Activity => Change_in_Circumstance => OnGetStageTransition")] // AutoGenerated
    internal class when_change_in_circumstance : WorkflowSpecDebtCounselling
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_Change_in_Circumstance(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}