using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.States.Common_Rework.OnEnter
{
    [Subject("State => Common_Rework => OnEnter")] // AutoGenerated
    internal class when_common_rework : WorkflowSpecCap2
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Rework(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}