using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities.Accept.OnGetStageTransition
{
    [Subject("Activity => Accept => OnGetStageTransition")] // AutoGenerated
    internal class when_accept : WorkflowSpecDebtCounselling
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_Accept(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}