Use [2am]
go

IF EXISTS (SELECT TOP 1 * FROM test.AutomationLeads)
	BEGIN
		TRUNCATE TABLE test.AutomationLeads
		PRINT 'TRUNCATED TABLE AutomationLeads'
	END

insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','Branch Consultant Test','Case01','Test','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','Afrikaans','English','Alive','ReAssignConsultantLead',0,'sahl\bcuser7','sahl\bcuser5',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Miss','T','Branch Consultant Test','Case02','Test','Female','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','AssignAdminLead',0,'sahl\bcuser5','sahl\bcuser7',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','NTU Lead','Test','NTU','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','AppNotAcceptedLead',0,'sahl\bcuser7','sahl\bcuser5',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','AppNotAcceptedFinalised Lead','Test','NTU','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','AppNotAcceptedFinalisedLead',0,'sahl\bcuser5','sahl\bcuser7',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','ReactivateAppNotAccepted Lead','Test','NTU','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','ReactivateAppNotAcceptedLead',0,'sahl\bcuser7','sahl\bcuser5',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','AppNotAcceptedArchiveApplication Lead','Test','NTU','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','AppNotAcceptedArchiveApplicationLead',0,'sahl\bcuser5','sahl\bcuser7',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','AppNotAcceptedArchiveApplication Lead','Test','NTU','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','CreateApplicationFromLead',0,'sahl\bcuser5','sahl\bcuser7',1,'Consultant')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','Branch Admin Test','Case01','Test','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','Afrikaans','English','Alive','ReAssignAdminLead',0,'sahl\bauser','sahl\bauser1',1,'Admin')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Miss','T','Branch Admin Test','Case03','Test','Female','Single','Unknown','Unknown','SA Citizen','','T1231234','English','Afrikaans','Alive','ArchiveTimer',0,'sahl\bauser1','sahl\bauser3',1,'Admin')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mr','T','Estate Agent Lead','Re Assign','Test','Male','Single','Unknown','Unknown','SA Citizen','','T1231234','Afrikaans','English','Alive','ReAssignEstateAgentLead',0,'sahl\eacuser1','sahl\eacuser2',1,'EstateAgents')
insert into [2am].test.AutomationLeads (Role,IDNumber,Salutation,Initials,FirstNames,Surname,PreferredName,Gender,MaritalStatus,PopulationGroup,Education,CitizenshipType,PassportNumber,TaxNumber,HomeLanguage,DocumentLanguage,Status,TestIdentifier,OfferKey,OrigConsultant,ReAssignedConsultant,IsIncomeContributor,TestGroup) VALUES ( 'Lead - Main Applicant','','Mrs','T','Estate Agent Lead','Estate Agent Assign','Test','Female','Single','Unknown','Unknown','SA Citizen','','T1231234','Afrikaans','English','Alive','AssignEstateAgentLead',0,'sahl\eacuser1','sahl\eacuser2',1,'EstateAgents')
