using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Refresh_Application_Timeout.OnGetActivityMessage
{
    [Subject("Activity => Refresh_Application_Timeout => OnGetActivityMessage")] // AutoGenerated
    internal class when_refresh_application_timeout : WorkflowSpecApplicationCapture
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Refresh_Application_Timeout(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}