using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.States._45_Day_Reminder.OnExit
{
    [Subject("State => 45_Day_Reminder => OnExit")] // AutoGenerated
    internal class when_45_day_reminder : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnExit_45_Day_Reminder(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}