using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.Activities.Create_CAP2_lead.OnGetStageTransition
{
    [Subject("Activity => Create_CAP2_lead => OnGetStageTransition")] // AutoGenerated
    internal class when_create_cap2_lead : WorkflowSpecCap2
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_Create_CAP2_lead(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}