using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Return_to_Manage_Application.OnStart
{
    [Subject("Activity => Return_to_Manage_Application => OnStart")] // AutoGenerated
    internal class when_return_to_manage_application : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Return_to_Manage_Application(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}