using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Continue_with_Followup.OnComplete
{
    [Subject("Activity => Continue_with_Followup => OnComplete")] // AutoGenerated
    internal class when_continue_with_followup : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Continue_with_Followup(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}