using Machine.Specifications;

namespace WorkflowMaps.HelpDesk.Specs.Activities.Proceed.OnStart
{
    [Subject("Activity => Proceed => OnStart")] // AutoGenerated
    internal class when_proceed : WorkflowSpecHelpDesk
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Proceed(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}