using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.States.Awaiting_Timeout.OnEnter
{
    [Subject("State => Awaiting_Timeout => OnEnter")] // AutoGenerated
    internal class when_awaiting_timeout : WorkflowSpecApplicationCapture
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Awaiting_Timeout(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}