using Machine.Fakes;
using Machine.Specifications;
using SAHL.Core.BusinessModel.Enums;
using SAHL.Core.Services;
using SAHL.Core.SystemMessages;
using SAHL.Workflow.Shared;
using SAHL.Workflow.ThirdPartyInvoices;
using SAHL.WorkflowMaps.Specs.Common;

namespace SAHL.WorkflowMaps.ThirdPartyInvoices.Specs.Activities.Escalate_for_Approval.OnComplete
{
    [Subject("Activity => Escalate_for_Approval => OnComplete")] // AutoGenerated
    internal class when_invoking_the_domain_command_fails : WorkflowSpecThirdPartyInvoices
    {
        private static bool result;
        private static IWorkflowAssignment workflowAssignment;
        private static IThirdPartyInvoiceWorkflowProcess thirdPartyInvoices;

        private Establish context = () =>
        {
            ((ParamsDataStub)paramsData).Data = 12345;
            workflowAssignment = An<IWorkflowAssignment>();
            thirdPartyInvoices = An<IThirdPartyInvoiceWorkflowProcess>();
            workflowAssignment.WhenToldTo(x => x.AssignCaseToSpecificUserInCapability(Param.IsAny<ISystemMessageCollection>(), GenericKeyType.ThirdPartyInvoice, Param.IsAny<int>(),
                Param.IsAny<long>(), Capability.InvoiceApprover, Param.IsAny<IServiceRequestMetadata>(), Param.IsAny<int>())).Return(true);
            thirdPartyInvoices.WhenToldTo(x => x.EscalateThirdPartyInvoiceForApproval(Param.IsAny<ISystemMessageCollection>(), Param.IsAny<int>(), Param.IsAny<int>(),
                Param.IsAny<IServiceRequestMetadata>())).Return(false);
            domainServiceLoader.RegisterMockForType(workflowAssignment);
            domainServiceLoader.RegisterMockForType(thirdPartyInvoices);
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Escalate_for_Approval(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_not_invoke_the_domain_command = () =>
        {
            thirdPartyInvoices.WasToldTo(x => x.EscalateThirdPartyInvoiceForApproval(Param.IsAny<ISystemMessageCollection>(), Param.IsAny<int>(), Param.IsAny<int>(),
                Param.IsAny<IServiceRequestMetadata>()));
        };

        private It should_return_false = () =>
        {
            result.ShouldBeFalse();
        };
    }
}