using Machine.Specifications;

namespace WorkflowMaps.Life.Specs.Activities.isStandardCover.OnGetStageTransition
{
    [Subject("Activity => isStandardCover => OnGetStageTransition")] // AutoGenerated
    internal class when_isstandardcover : WorkflowSpecLife
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetStageTransition_isStandardCover(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}