using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Valuation_in_Order.OnComplete
{
    [Subject("Activity => Valuation_in_Order => OnComplete")] // AutoGenerated
    internal class when_valuation_in_order : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Valuation_in_Order(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}