using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.States.Common_Translate_.OnExit
{
    [Subject("State => Common_Translate_ => OnExit")] // AutoGenerated
    internal class when_common_translate_ : WorkflowSpecApplicationManagement
    {
        static bool result;
        Establish context = () =>
        {
            result = false;
        };
		
        Because of = () =>
        {
            result = workflow.OnExit_Common_Translate_(instanceData, workflowData, paramsData, messages);
        };

        It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}