using Machine.Specifications;

namespace WorkflowMaps.DebtCounselling.Specs.Activities._45_day_reminder_sent.OnComplete
{
    [Subject("Activity => 45_day_reminder_sent => OnComplete")] // AutoGenerated
    internal class when_45_day_reminder_sent : WorkflowSpecDebtCounselling
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_45_day_reminder_sent(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}