using Machine.Specifications;

namespace WorkflowMaps.ReadvancePayments.Specs.States.Common_Opt_Out_SuperLo.OnEnter
{
    [Subject("State => Common_Opt_Out_SuperLo => OnEnter")] // AutoGenerated
    internal class when_common_opt_out_superlo : WorkflowSpecReadvancePayments
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnEnter_Common_Opt_Out_SuperLo(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}