using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.OnReturnFurtherVal.OnStart
{
    [Subject("Activity => OnReturnFurtherVal => OnStart")] // AutoGenerated
    internal class when_onreturnfurtherval : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_OnReturnFurtherVal(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}