using Machine.Specifications;

namespace WorkflowMaps.Cap2.Specs.Activities.Rework_Offer.OnComplete
{
    [Subject("Activity => Rework_Offer => OnComplete")] // AutoGenerated
    internal class when_rework_offer : WorkflowSpecCap2
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            string message = string.Empty;
            result = workflow.OnCompleteActivity_Rework_Offer(instanceData, workflowData, paramsData, messages, ref message);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}