using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Instruct_Attorney.OnGetActivityMessage
{
    [Subject("Activity => Instruct_Attorney => OnGetActivityMessage")] // AutoGenerated
    internal class when_instruct_attorney : WorkflowSpecApplicationManagement
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Instruct_Attorney(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}