//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAHL.Web.Views.ReleaseAndVariations {
    
    public partial class ReleaseAndVariationsSummary {
        protected System.Web.UI.WebControls.Panel pnlContact;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblAccountName;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblAccountNumber;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblLinkedToOffer;
        protected SAHL.Common.Web.UI.Controls.SAHLDropDownList ddlRequestType;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblRequestType;
        protected SAHL.Common.Web.UI.Controls.SAHLDropDownList ddlApplyChangeTo;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblApplyChangeTo;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblLoanBalance;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblArrears;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblSPV;
        protected System.Web.UI.WebControls.Panel pnlMemo;
        protected SAHL.Common.Web.UI.Controls.SAHLTextBox txtNotes;
        protected System.Web.UI.WebControls.Panel pnlLoanDetails;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblCurrentLTV;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblCurrentPTI;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblCurrentLoan;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblProducts;
        protected System.Web.UI.WebControls.Panel pnlBondDetails;
        protected SAHL.Common.Web.UI.Controls.SAHLGridView gridBondDetails;
        protected System.Web.UI.WebControls.Panel pnlConditions;
        protected SAHL.Common.Web.UI.Controls.SAHLGridView gridConditions;
        protected SAHL.Common.Web.UI.Controls.SAHLLabel lblCaption;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnConfirm;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnCancel;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnSubmit;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnPrintRequest;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnUpdateSummary;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnUpdateConditions;
        protected SAHL.Common.Web.UI.Controls.SAHLButton btnERFInformation;
    }
}
