using Machine.Specifications;

namespace WorkflowMaps.ApplicationCapture.Specs.Activities.Select_Estate_Agent_or_Agency.OnGetActivityMessage
{
    [Subject("Activity => Select_Estate_Agent_or_Agency => OnGetActivityMessage")] // AutoGenerated
    internal class when_select_estate_agent_or_agency : WorkflowSpecApplicationCapture
    {
        private static string result;

        private Establish context = () =>
        {
            result = "abcd";
        };

        private Because of = () =>
        {
            result = workflow.GetActivityMessage_Select_Estate_Agent_or_Agency(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_an_empty_string = () =>
        {
            result.ShouldBeTheSameAs(string.Empty);
        };
    }
}