using Machine.Specifications;

namespace WorkflowMaps.ApplicationManagement.Specs.Activities.Return_Processor_Credit.OnStart
{
    [Subject("Activity => Return_Processor_Credit => OnStart")] // AutoGenerated
    internal class when_return_processor_credit : WorkflowSpecApplicationManagement
    {
        private static bool result;

        private Establish context = () =>
        {
            result = false;
        };

        private Because of = () =>
        {
            result = workflow.OnStartActivity_Return_Processor_Credit(instanceData, workflowData, paramsData, messages);
        };

        private It should_return_true = () =>
        {
            result.ShouldBeTrue();
        };
    }
}