// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DecisionTreeTestSuiteTemplate : DecisionTreeTestSuiteTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Collections.Generic;\r\nusing SAHL.Tools.DecisionTree.TestRunner.Inter" +
                    "faces;\r\nusing SAHL.DecisionTree.TreeTests.Models;\r\n\r\nnamespace ");
            
            #line 10 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 12 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TestSuiteName));
            
            #line default
            #line hidden
            this.Write(" : ITestSuite\r\n    {\r\n        public IEnumerable<ITestCase> TestCases { get; set;" +
                    " }\r\n    \r\n        public ");
            
            #line 16 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TestSuiteName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            this.TestCases = new List<ITestCase> \r\n            {\r\n" +
                    "");
            
            #line 20 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach (var testCase in TestCases) { 
            
            #line default
            #line hidden
            this.Write("                new TestCase(\"");
            
            #line 21 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Name));
            
            #line default
            #line hidden
            this.Write("\", \r\n                    new List<ITestInput> { \r\n\r\n");
            
            #line 24 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var input in testCase.Inputs) { 
            
            #line default
            #line hidden
            this.Write("                        new TestInput (\"");
            
            #line 25 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(input.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 25 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(input.Type));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 25 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(input.Value));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 25 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(input!=testCase.Inputs.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 26 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 27 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                    },\r\n                    new List<IScenario> {\r\n");
            
            #line 31 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var scenario in testCase.Scenarios) { 
            
            #line default
            #line hidden
            this.Write("                        new Scenario(\"");
            
            #line 32 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scenario.Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n                            new List<ITestInput> { \r\n");
            
            #line 34 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var inputVar in scenario.Inputs) { 
            
            #line default
            #line hidden
            this.Write("                                new TestInput(\"");
            
            #line 35 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputVar.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 35 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputVar.Type));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 35 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputVar.Value));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 35 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(inputVar!=scenario.Inputs.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 36 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 37 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                            },\r\n                            new List<ITestOutpu" +
                    "t> {\r\n");
            
            #line 41 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var outputVar in scenario.ExpectedOutputs) { 
            
            #line default
            #line hidden
            this.Write(" \r\n                                new TestOutput(\"");
            
            #line 42 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputVar.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputVar.Assertion));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputVar.Type));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputVar.ExpectedValue));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 42 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(outputVar!=scenario.ExpectedOutputs.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 43 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 44 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                            },\r\n                            new List<IOutputMes" +
                    "sage> {\r\n");
            
            #line 48 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var outputMessage in scenario.ExpectedMessages) { 
            
            #line default
            #line hidden
            this.Write("                                new OutputMessage(\"");
            
            #line 49 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputMessage.ExpectedMessage));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 49 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputMessage.Assertion));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 49 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputMessage.ExpectedMessageSeverity));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 49 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(outputMessage!= scenario.ExpectedMessages.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 50 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 51 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                            },\r\n                            new List<ISubtreeEx" +
                    "pectation> {\r\n");
            
            #line 55 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 foreach(var expectedSubtree in scenario.SubtreeExpectations) { 
            
            #line default
            #line hidden
            this.Write("                                new SubtreeExpectation(\"");
            
            #line 56 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expectedSubtree.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 56 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expectedSubtree.Assertion));
            
            #line default
            #line hidden
            this.Write("\")");
            
            #line 56 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(expectedSubtree != scenario.SubtreeExpectations.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 57 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 58 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                            })");
            
            #line 60 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if (scenario != testCase.Scenarios.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 61 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 62 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                    })");
            
            #line 64 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 if(testCase != TestCases.Last()) { 
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 65 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 66 "C:\git\blue\dev\Tools\General\src\SAHL.Tools.DecisionTreeTestFromJsonGenerator.Lib\Templates\DecisionTreeTestSuiteTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            };\r\n        }\r\n    }\r\n}\r\n\r\n\r\n ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class DecisionTreeTestSuiteTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
